<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class clinicalservices_nursing extends Model
{
    protected $fillable=[
        "bath_day",
        "bath_night",
        "oral_care_day",
        "oral_care_night",
        "pressure_area_care_day",
        "pressure_area_care_night",
        "breathing_adequately_day",
        "breathing_adequately_night",
        "monitor_saturation_day",
        "monitor_saturation_night",
        "oxygen_accordingly_day",
        "oxygen_accordingly_night",
        "diet_plan_day",
        "diet_plan_night",
        "oral_feedingday",
        "oral_feedingnight",
        "nasogastric_tube_feeding_day",
        "nasogastric_tube_feeding_night",
        "parental_day",
        "parental_night",
        "passing_urine_adequately_day",
        "passing_urine_adequately_night",
        "opening_bowels_adequatelyday",
        "opening_bowels_adequatelynight",
        "excessive_sweating_day",
        "excessive_sweating_night",
        "aeo_day",
        "aeo_night",
        "pen_day",
        "pen_night",
        "ps_day",
        "ps_night",
        "mobilised_day",
        "mobilised_night",
        "nutri_counselling_day",
        "nutri_counselling_night",
        "gen_counselling_day",
        "gen_counselling_night",
        "medications_6_am",
        "medications_12_mid",
        "medications_2_pm",
        "medications_6_pm",
        "medications_10_pm",
        "vital_observations_6_am",
        "vital_observations_10_am",
        "vital_observations_2_pm",
        "vital_observations_6_pm",
        "vital_observations_10_pm",
        "gcs_day",
        "gcs_night",
        "cannular_observations_6_am",
        "cannular_observations_10_am",
        "cannular_observations_2_pm",
        "cannular_observations_6_pm",
        "cannular_observations_10_pm",
        "hes_day",
        "hes_night",
        "din_day",
        "din_night",
        "cdf_day",
        "cdf_night",
        "mna_day",
        "mna_night",
        "ba_day",
        "ba_night",
        "bran_day",
        "bran_night",
        "sic_day",
        "sic_night",
        "icm_day",
        "icm_night",
        "irfu_day",
        "irfu_night",
        "nok_day",
        "nok_night",
        "ar_day",
        "ar_night",
        "apmc_day",
        "apmc_night",
        "ni_day",
        "ni_night",
        "check_hod_day",
        "check_hod_night",
        'administration_patient_informations_id', 'institution_id', 'user_id'
    ];
    public function patient(){
        return $this->belongsTo(administration_patient_information::class);
    }
}
